- name: Install some core packages
  tags: packages
  become: yes
  community.general.pacman:
    name:
      - vim
      - mpv
      - fortune-mod
      - man
      - alacritty
      - zathura
      - dhcpcd
      - ntp
      - ttf-hack-nerd
      - ttf-joypixels
      - unicode-emoji
      - vimiv
      - swaybg
      - xdg-desktop-portal-wlr
      - xorg-xwayland
      - grim
      - slurp
      - brightnessctl
      - ydotool
      - bemenu
      - bemenu-wayland
      - firefox
      - git
      - base-devel
      - tmux
      - pcmanfm-gtk3
      - keepassxc
      - nextcloud-client
      - discord
      - signal-desktop
      - udisks2
      - dunst
      - thunderbird
      - wl-clipboard
      - ripgrep
      - fzf
      - tldr
      - rsync
      - starship
      - blueman
      - bluez
      - bluez-utils
      - unzip
      - htop
    state: present
    
   

