---

- name: Clone paru repo
  tags: paru
  become: no
  ansible.builtin.git:
    repo: 'https://aur.archlinux.org/paru.git'
    dest: /home/spam/Clones/paru

- name: Ensure build dependencies
  tags: paru
  community.general.pacman:
    name:
      - base-devel
    state: present

- name: Build paru
  tags: paru
  become: no
  ansible.builtin.shell: makepkg -si
  args:
    chdir: /home/spam/Clones/paru
