---
- name: Print some debug information
  vars:
    msg: |
      
      

      Enable Pacman parallell Downloads!
      --------------------------------
      sudoedit /etc/pacman.conf
      ================================
      
      
      

      Add hid_sensort_hub blacklist
      --------------------------------
      see:
      https://wiki.archlinux.org/title/Framework_Laptop#Changing_the_brightness_of_the_monitor_does_not_work
      ================================


      

      Setup PW-Manager, SSH keys and GPG
      --------------------------------
      Log into nextcloud
      ================================



      
      Change Repo Origins
      --------------------------------
      For this repo and dotfiles
      ================================




      Unstow .dotfiles if not done already
      --------------------------------
      stow -vt ~ *
      ================================



      
      Setup git signing and git-delta
      --------------------------------
      edit global .gitconfig
      ================================



      
      
  debug:
    msg: "{{ msg.split('\n') }}"
  tags: todos
